[project]
name = "fly-in"
version = "0.1.0"
description = "Drone routing system that navigates multiple drones
through connected zones while minimizing simulation turns and handling movement"
readme = "README.md"
authors = [
    { name = "mabravo-"}
]

requires-python = ">=3.12"
dependencies = []

[tool.uv]
package = false

python_version = "3.12"
warn_return_any = true
warn_unused_ignores = true
ignore_missing_imports = true
disallow_untyped_defs = true
check_untyped_defs = true

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "flake8",
    "mypy",
]